services:
  postgres-test:
    image: 'postgres:18.1'
    container_name: flossrennen-test-db-container
    environment:
      POSTGRES_DB: flossrennen-test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network-test:
    name: flossrennen-network-test
    driver: bridge