services:
  postgres-dev:
    image: 'postgres:18.1'
    container_name: flossrennen-dev-db-container
    restart: unless-stopped
    environment:
      POSTGRES_DB: flossrennen-dev-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5433:5432'
    volumes:
      - db-data-dev:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data-dev:
    name: flossrennen-dev-db

networks:
  app-network-dev:
    name: flossrennen-network-dev
    driver: bridge